import type { Metadata } from "next";
import { Inter } from "next/font/google";

import CustomCursor from "@/components/CustomCursor/CustomCursor";
import SmoothScrollProvider from "@/components/SmoothScrollProvider/SmoothScrollProvider";
import Footer from "@/components/Footer/Footer";

import "@/styles/globals.scss";

const interSans = Inter({
    variable: "--font-inter-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="de">
            <body className={`${interSans.variable}`}>
                <CustomCursor />
                <SmoothScrollProvider>
                    <main>{children}</main>
                    <Footer />
                </SmoothScrollProvider>
            </body>
        </html>
    );
}
